codecov:
  notify:
    after_n_builds: 3
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

comment:
  after_n_builds: 3
  layout: "diff,flags,files"
  behavior: default
  require_changes: yes

github_checks:
  annotations: true

flag_management:
  individual_flags:
    - name: smart-tests
      carryforward: true
      carryforward_mode: "labels"
      statuses:
        - type: "project"
        - type: "patch"